{
  parserClass="com.bloxbean.intelliada.idea.aiken.lang.parser.AikenParser"
  parserUtilClass="com.bloxbean.intelliada.idea.aiken.lang.psi.impl.AikenParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Aiken"
  psiImplClassSuffix="Impl"
  psiPackage="com.bloxbean.intelliada.idea.aiken.lang.psi"
  psiImplPackage="com.bloxbean.intelliada.idea.aiken.lang.psi.impl"

  elementTypeHolderClass="com.bloxbean.intelliada.idea.aiken.lang.psi.AikenTypes"
  elementTypeClass="com.bloxbean.intelliada.idea.aiken.lang.psi.AikenElementType"
  tokenTypeClass="com.bloxbean.intelliada.idea.aiken.lang.psi.AikenTokenType"

  psiImplUtilClass="com.bloxbean.intelliada.idea.aiken.lang.psi.impl.AikenPsiImplUtil"


tokens = [
        // Keywords
        IF = "if"
        ELSE = "else"
        WHEN = "when"
        IS = "is"
        FN = "fn"
        USE = "use"
        LET = "let"
        PUB = "pub"
        TYPE = "type"
        OPAQUE = "opaque"
        CONST = "const"
        TODO = "todo"
        EXPECT = "expect"
        CHECK = "check"
        TEST = "test"
        TRACE = "trace"
        FAIL = "fail"
        VALIDATOR = "validator"
        AND = "and"
        OR = "or"
        AS = "as"
        VIA = "via"
        BENCHMARK = "benchmark"

        MINT = "mint"
        SPEND = "spend"
        WITHDRAW = "withdraw"
        PUBLISH = "publish"
        VOTE = "vote"
        PROPOSE = "propose"

        //check if required??
        EXTERNAL = "external"

        // Regexp
        IDENTIFIER = "regexp:[_a-z][_0-9a-z]*"
        UPPER_IDENTIFIER = "regexp:[A-Z][_0-9a-zA-Z]*"

        COMMENT = "regexp://([^\n]*)?"
        DOC_COMMENT = "regexp:///([^\n]*)?"
        MODULE_COMMENT = "regexp:////([^\n]*)?"

        NUMBER = "regexp:[0-9]+"
        HEX_NUMBER = "regexp:0x[0-9a-fA-F]+"
        BYTE_STRING = "regexp:#\"([^\\\\\\\\\\\\\\\\\\\"\\\\\\\\]|\\\\\\\\\\\\\\\\[^efnrt\\\\\\\"\\\\\\\\\\\\\\\\])*\""
        STRING_CONTENT = "regexp:\"([^\\\\\\\"]|\\\\[^efnrt\\\"\\\\])+\"" // TODO improve matching for string content

        // Chars
        LBRACE      =  '{'
        RBRACE      =  '}'
        LBRACK      =  '['
        RBRACK      =  ']'
        LPAREN      =  '('
        RPAREN      =  ')'

        COLON       =  ':'
        SEMICOLON   =  ';'
        QUESTION    =  '?'
        HASH        =  '#'

        COMMA       =  ','

        EQ          =  '='
        EQEQ        =  '=='
        NE          =  '!='
        LE          =  '<='
        GE          =  '>='

        BANG        =  '!'

        PLUS        =  '+'
        MINUS       =  '-'
        PLUSDOT     =  '+.'
        MINUSDOT    =  '-.'
        STARDOT     =  '*.'
        SLASHDOT    =  '/.'
        PERCENT     =  '%'

        OR          =  '||'
        AND         =  '&&'

        LT          =  '<'
        GT          =  '>'

        MUL         =  '*'
        DIV         =  '/'
        DIVDIV      =  '//'

        DOT         =  '.'
        DOTDOT      =  '..'

        FAT_ARROW   =  '=>'
        ARROW       =  '->'
        BACK_ARROW  =  '<-'

        QUOTE       =  '"'

        PIPE        =  '|>'
        BITWISE_OR  =  '|'
    ]
}

aikenFile ::= topLevelDefinition*
private topLevelDefinition ::=
    importStatement
    | typeStatement
    | validatorStatement
    | functionStatement
    | testStatement
    | benchmarkStatement
    | COMMENT
    | DOC_COMMENT
    | MODULE_COMMENT
    | ([PUB] constantStatement)

private innerDefinition ::=
    COMMENT
    | variableStatement
    | constantStatement
    | functionCall

typeIdentifier ::= [IDENTIFIER DOT] UPPER_IDENTIFIER [LPAREN typeIdentifierInnerType [typeIdentifierInnerType*] RPAREN]
typeIdentifierInnerType ::= typeIdentifier [COMMA]

private constructorElement ::= constructorIdentifier typeIdentifier [COMMA]
constructorIdentifier ::= IDENTIFIER COLON

importStatement ::= USE importStatementElement
importStatementElement ::= IDENTIFIER ('/' IDENTIFIER [importStatementTypes])*
importStatementTypes ::= DOT LBRACE ((UPPER_IDENTIFIER|IDENTIFIER) [COMMA])* RBRACE

// TODO improve type statement parsing
typeName ::= UPPER_IDENTIFIER
constructorName ::= UPPER_IDENTIFIER
typeStatement ::= [PUB] TYPE typeName ('<' IDENTIFIER '>')? LBRACE (constructorElement | (typeStatementConstructor | typeStatementConstructorNoArg)*) RBRACE
typeStatementConstructor ::= constructorName (LBRACE|LPAREN) (constructorElement | IDENTIFIER)* (RBRACE|RPAREN)
typeStatementConstructorNoArg ::= constructorName

validatorStatement ::=  VALIDATOR IDENTIFIER [LPAREN [(constructorElement)*] RPAREN] LBRACE [innerDefinition*] RBRACE

functionStatement ::= [PUB] FN IDENTIFIER LPAREN [(constructorElement)*] RPAREN [functionStatementType] LBRACE [innerDefinition*] RBRACE
functionStatementType ::= ARROW typeIdentifier

variableStatement ::= LET IDENTIFIER EQ variableValue
constantStatement ::= CONST IDENTIFIER EQ variableValue

// TODO parse value inside string
variableValue ::= whenExpression | ifExpression | functionCall | listExpression | tupleExpression | recordExpression | UPPER_IDENTIFIER | typeIdentifier | IDENTIFIER | NUMBER | HEX_NUMBER | BYTE_STRING | STRING_CONTENT | booleanLiteral

booleanLiteral ::= "True" | "False"

listExpression ::= LBRACK [variableValue (COMMA variableValue)*] RBRACK

tupleExpression ::= LPAREN variableValue (COMMA variableValue)+ RPAREN

recordExpression ::= UPPER_IDENTIFIER LBRACE [recordField (COMMA recordField)*] RBRACE
recordField ::= IDENTIFIER COLON variableValue

ifExpression ::= IF variableValue LBRACE [innerDefinition*] RBRACE [ELSE LBRACE [innerDefinition*] RBRACE]

whenExpression ::= WHEN variableValue IS LBRACE whenClause* RBRACE
whenClause ::= pattern ARROW variableValue

pattern ::= IDENTIFIER | UPPER_IDENTIFIER | listPattern | tuplePattern | recordPattern | literalPattern
listPattern ::= LBRACK [pattern (COMMA pattern)*] RBRACK
tuplePattern ::= LPAREN pattern (COMMA pattern)+ RPAREN
recordPattern ::= UPPER_IDENTIFIER LBRACE [patternField (COMMA patternField)*] RBRACE
patternField ::= IDENTIFIER [COLON pattern]
literalPattern ::= NUMBER | HEX_NUMBER | STRING_CONTENT | BYTE_STRING | booleanLiteral

testStatement ::= TEST IDENTIFIER LBRACE [innerDefinition*] RBRACE
benchmarkStatement ::= BENCHMARK IDENTIFIER LBRACE [innerDefinition*] RBRACE

functionCall ::= [IDENTIFIER DOT] IDENTIFIER LPAREN [functionCallParam*] RPAREN [PIPE functionCall]
functionCallParam ::= ((IDENTIFIER COLON variableValue) | variableValue)[COMMA]
